version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        ### uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: dooboolab-secret-123
        ### comment if you want to Local testing
        databases:
          default:
            connector: mysql
            host: talktalk-mysql.mysql.database.azure.com
            user: dooboolab@talktalk-mysql
            password: dooboolab!
            rawAccess: true
            port: 3306
            migrations: true
        ### uncomment if you want to Local testing
        # databases: 
        #   default:
        #     connector: mysql
        #     host: mysql
        #     port: 3306
        #     user: root
        #     password: prisma
        #     migrations: true
        #     rawAccess: true
  ### comment if you want to Local testing
  # mysql:
  #   image: mysql:5.7
  #   # restart: always
  #   environment:
  #       MYSQL_DATABASE: talktalk
  #       MYSQL_USER: dooboolab
  #       MYSQL_PASSWORD: dooboolab!
  #       MYSQL_ROOT_PASSWORD: Dooboolab123!
  #   # volumes:
  #     # - mysql:/var/lib/mysql
  ### uncomment if you want to Local testing
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33061:3306"
### uncomment if you want to Local testing
volumes:
  mysql:
