version: '3.3'

services:
  prisma:
    build: prisma
    ports:
    - "4466:4466"
    env_file: .env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: ${PRISMA_DB_CONNECTOR:-mysql}
            host: ${PRISMA_DB_HOST:-mysql}
            port: ${PRISMA_DB_PORT:-3306}
            # https://github.com/prisma/prisma/issues/2506
            user: ${PRISMA_DB_USER:-root}
            password: ${PRISMA_DB_PASSWORD:-prisma}
            rawAccess: ${PRISMA_DB_RAW_ACCESS:-true}
            migrations: ${PRISMA_DB_MIGRATIONS:-true}
    # volumes:
      # - /etc/localtime:/etc/localtime:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: ${PRISMA_DB_USER:-prisma}
      MYSQL_PASSWORD: ${PRISMA_DB_PASSWORD:-prisma}
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ${PRISMA_DB_PASSWORD:-prisma}
      # https://github.com/prisma/prisma/issues/2506
      MYSQL_DATABASE: ${PRISMA_DB_DATABASE:-prisma}
    volumes:
      - mysql:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro

volumes:
  mysql:
